import turtle

screen = turtle.Screen()
screen.setup(500, 400)
screen.title("P0")
screen.colormode(255)
screen.bgcolor("lightyellow")
screen.tracer(0)
t = turtle.Turtle()
t.speed(0)
t.pensize(4)
t.color((255, 0, 0), "#00ff00")
t.begin_fill()
for _ in range(3):
    t.fd(80)
    t.lt(120)
t.end_fill()
t.penup(); t.setx(-100); t.sety(50); t.pendown()
t.pencolor("navy"); t.fillcolor("orange")
t.circle(30, 270)
t.dot(25, "purple")
t.penup(); t.goto(60, -80); t.setheading(45); t.pendown()
t.write("Olá", font=("Arial", 16, "bold"))
t.write("meio", align="center", font=("Courier", 10, "normal"))
t.hideturtle(); t.showturtle()
t.home()
t.backward(30)
screen.update()
u = turtle.Turtle()
u.color("green")
u.forward(20)
u.clear()
u.reset()
u.right(90); u.forward(40)
turtle.done()
