"""Generate turtleweb/_colors.py from the real Tk color table (run with xvfb-run)."""
import re
import tkinter

names = set()
with open("/usr/share/X11/rgb.txt") as fh:
    for line in fh:
        m = re.match(r"\s*\d+\s+\d+\s+\d+\s+(.+?)\s*$", line)
        if m:
            names.add(m.group(1).lower().replace(" ", ""))
root = tkinter.Tk()
table = {}
for n in sorted(names):
    try:
        r, g, b = root.winfo_rgb(n)
    except tkinter.TclError:
        continue
    table[n] = "#%02x%02x%02x" % (r >> 8, g >> 8, b >> 8)
lines = ['"""Tk color names (lowercase, no spaces) -> #rrggbb. Generated by tools/gen_colors.py."""', "", "TK_COLORS = {"]
lines += ['    "%s": "%s",' % kv for kv in table.items()]
lines.append("}")
open("turtleweb/_colors.py", "w").write("\n".join(lines) + "\n")
print(len(table), table["green"], table["lightblue"], table["gray50"])
